### ISSUE TITLE
Remove Segment analytics integrations

### ISSUE THREAD

**Issue by ghost** [okgrow/auto-analytics#1]
Remove the Segment.io third-party analytics integrations in favor of installing individual npm packages for each of these.

NOTE: This depends on individual npm packages being available which may not be at this time.

**Comment by ghost** [comment]
We plan to address this issue by unbundling the currently embedded customized Segment `analytics.js` module which will allow much greater flexibility by having users of _this_ package install what they need from Segment’s module.” You will see this coming in version 4.0.0 of _this_ package and version 2.0.0 of the https://github.com/okgrow/auto-analytics package in the next couple of weeks.

**Comment by cfnelson** [comment]
This enhancement will be completed once this [PR #9](https://github.com/okgrow/auto-analytics/pull/9) is merged & published.

**Comment by cfnelson** [comment]
We no longer bundle Segment's `analytics.min.js` by default. This will significantly decrease the bundle size thanks to only bundling the integrations you are using. Please refer to [README](https://github.com/okgrow/auto-analytics#creating-segments-analyticsjs) for instructions on how to build your own analytics integration bundle. This change was introduce in 
[v2.0.0](https://github.com/okgrow/auto-analytics/releases/tag/v2.0.0) 🔥
