### ISSUE TITLE
Option for LinkedIn analytics

### ISSUE THREAD

**Issue by sarabsilveira** [okgrow/auto-analytics#20]
Hi,

I've been trying to use the package with LinkedIn Analytics, but don't seem to find the correct option.

Is there one?

Thanks!
Sara

**Comment by RichardLitt** [comment]
I believe this _should_ work if you add in the appropriate config and  and ID in the settings. Can you provide an obfuscated example?

**Comment by sarabsilveira** [comment]
That would be my impression as well. My only problem is getting to know the key for it. As for google analytics would be` Google Analytics`.

**Comment by RichardLitt** [comment]
@cfnelson Is there a closed set of key names? I couldn't find that in the sourcecode.

**Comment by sarabsilveira** [comment]
Google Analytics one I got from an example. I also know that for Twitter will be TwitterAds (got it from the code). But I don't have a clue for Linked In...

**Comment by cfnelson** [comment]
@sarabsilveira The only LinkedIn Analytics I could find reference to was [LinkedIn Insight Tag]( https://segment.com/integrations/linkedin-insight-tag) however segments [docs](https://segment.com/docs/destinations/linkedin-conversion-tag/) state that they don't integrate the LinkedIn Analytics with their API as it does its own reporting (I am unsure what data/events they track as I haven't used the service before). I believe the suggested way to add LinkedIn Analytics is to just add the script yourself to your website see LinkedIn Docs [here](https://www.linkedin.com/help/linkedin/answer/65513). Hope this is helpful for you. :)

For reference for anyone else, if you want to see what Segment Analytic integrations are available you can search their github repo [here](https://github.com/segment-integrations?utf8=%E2%9C%93&q=&type=&language=) or you can look at the source code here which lists all the analytic integration modules [here](https://github.com/okgrow/analytics.js/blob/master/analytics.js#L43) cc @RichardLitt Hope this is what you were looking for. These links I referenced are in the Readme but maybe they should be promoted better/moved to the start of the Readme.

**Comment by RichardLitt** [comment]
Thanks @cfnelson. Looking through again, it is clearer to me that one needs to use Segments documentation to supplement the README docs. I'll keep this in mind for future issues. For now, I don't think there's a change needed.
