### ISSUE TITLE
Using analytics.js on node server?

### ISSUE THREAD

**Issue by Kiel-H-Byrne** [okgrow/auto-analytics#23]
Greetings, I utilized the suggested "build my own analytics.js file" without all the un-needed integrations, however the built `analytics.js` file has a bunch of references to the `window` global, so i can't use it on the server...

am i to install the `analytics-node` package from segment.io in order to use this? And if so, then why do i need the okgrow package? 

Thanks for helping. 

my code is simple, using meteor.js; i have a methods.js file in a common folder (accessible both by client and server) 
when the file is loaded, the server fails with: 
`ReferenceError: window is not defined`

thanks for any help

**Comment by cfnelson** [comment]
@tdotholla This pkg is for providing a router agnostic client side analytics and was designed to only run in the browser, it's not intended to be used for server side analytics. 

Check out the example folder to see how to use this pkg, if you move your code to the client you should be able to get it working. 

If your looking for server side analytics then you will need to use a different pkg.

Hope this clarifies everything, if you have any other questions, we will be happy to help 😃
