### ISSUE TITLE
build failed due to peerinvalid (eslint version)

### ISSUE THREAD

**Issue by peernohell** [okgrow/auto-analytics#24]
Hello every one 👋 

I'm alone to have this issue on a fresh git clone?
```
 npm run build

> @segment/analytics.js@2.11.0 build /Users/peernohell/tmp/okgrow-analytics.js
> make build

npm WARN engine string-width@2.1.1: wanted: {"node":">=4"} (current: {"node":"0.12.18","npm":"2.15.11"})
npm WARN engine esprima@4.0.1: wanted: {"node":">=4"} (current: {"node":"0.12.18","npm":"2.15.11"})
npm WARN engine strip-ansi@4.0.0: wanted: {"node":">=4"} (current: {"node":"0.12.18","npm":"2.15.11"})
npm WARN engine is-fullwidth-code-point@2.0.0: wanted: {"node":">=4"} (current: {"node":"0.12.18","npm":"2.15.11"})
npm WARN engine ansi-regex@3.0.0: wanted: {"node":">=4"} (current: {"node":"0.12.18","npm":"2.15.11"})
npm WARN engine esrecurse@4.2.1: wanted: {"node":">=4.0"} (current: {"node":"0.12.18","npm":"2.15.11"})
npm ERR! Darwin 17.7.0
npm ERR! argv "/Users/peernohell/.nvm/versions/node/v0.12.18/bin/node" "/Users/peernohell/.nvm/versions/node/v0.12.18/bin/npm" "install"
npm ERR! node v0.12.18
npm ERR! npm  v2.15.11
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package eslint@2.13.1 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer eslint-plugin-react@2.7.1 wants eslint@>=0.8.0 || ~1.0.0-rc-0
npm ERR! peerinvalid Peer eslint-config-segment@1.0.18 wants eslint@0.x
```

To fix it I remove in eslintrc file the extends property + I have change the version of eslint to 0.8.0 and the build worked.

It would be ownsome if version can be fixed (downgrade the eslint version in the package.json or update eslint dependances)

Thanks for all the works :)

**Comment by RichardLitt** [comment]
I didn't get this issue. Can you clarify your npm and node versions?

**Comment by peernohell** [comment]
As it's write in the log
node v0.12.18
npm v2.15.11

I just do a fresh git clone
nvm 0.12 (as it's seems that project work on an old npm)
npm install
make build

**Comment by cfnelson** [comment]
@peernohell We haven't been supporting node `v0.12.18` for quite some time now, I would recommend upgrading your `npm` & `node` versions to the latest active `node` release e.g v8 or higher. 

The logs itself suggest that you need node `v4` at minimum and some of those pkgs in the warnings I don't recognise as being apart of this library. This pkg should work for node `v4` but we never developed or supported anything older then this. Node `v4` is also now unsupported. See here for the release cycles of [node](https://github.com/nodejs/Release#lts-schedule).

**Comment by RichardLitt** [comment]
@peernohell You're right, they are listed there! Sorry for missing that. Thanks for following up, @cfnelson.

**Comment by peernohell** [comment]
It works 😃 
I just test with node 8 and it works perfectly.
The mistake is that I have try with version 4 and it didn't work, and as the analytics.js from segment work with an old 0.12 I have try it and it didn't work so I have fix the issue. I never though it will work with 8.
It would be very helpfull if the node version was written in the readme and/or in the package.json https://stackoverflow.com/a/29349773/958898

**Comment by RichardLitt** [comment]
Glad you got it working! And thanks for the PR!
