### ISSUE TITLE
Change settings reactively 

### ISSUE THREAD

**Issue by 55** [okgrow/auto-analytics#4]
I am trying to update `settings` object reactively. E.g.: https://github.com/apinf/platform/blob/6beaefb18dd34ec495d35a1c7634151d834ae4a8/core/client/analytics.js#L13-L26
```js
  // Get branding
  const branding = Branding.findOne();

  if (branding) {
    const googleAnalytics = branding.analytics.googleAnalytics;

    if (googleAnalytics) {
      const settings = {
        'Google Analytics': { trackingId: googleAnalytics },
      };
      // Run OKGrow analytics
      okGAnalytics(settings);
    }
  }
```

It might take whatever value from settings.json or directly from `const settings = { 'Google Analytics': { trackingId: 'test value' }};` only once and `okGAnalytics(settings);` never runs a second time. 

Is there a way to update the `settings` object reactively?

**Comment by cfnelson** [comment]
@55 As far as I am aware you can only instantiate `analytics.js` once, you can have multiple clients with their node.js lib [instead](https://segment.com/docs/sources/server/node/#multiple-clients).

I am unsure if segment.io will allow you to remove the default ga trackingID. But if they do then the I think the below snippet should work (Note: I haven't tested). If there is an issue it is likely with segment.io's `analytics.js` or their ga integration [package](https://github.com/segment-integrations/analytics.js-integration-google-analytics).

Let me know if you do end up getting it to work, as would be happy to accept a PR for documentation or as a feature/enhancement. 
```js
analytics.ready(() => {
  ga('remove'); // Removes the default or ga('nameOfMyTracker.remove'); if you know the name
  ga('create', 'UA-XXXXX-Y', 'auto'); // New key, can set extra fields here.
});
```
If the above doesn't work you can [add multiple trackers](https://segment.com/docs/integrations/google-analytics/#multiple-trackers) but you will manually have to send the event to the 2nd tracker.

If you are only needing to wait for the trackingId for a specific company/branding once for each client. I would suggest waiting until you have the correct id before calling `okGAnalytics(settings);`.

**Comment by 55** [comment]
@cfnelson thank you for your answer! 
In your example, where do you define `ga`?

**Comment by cfnelson** [comment]
@55 `ga` is the google analytics instance, it is globally defined on the client and is defined by segment.io's  analytics.js integration for google analytics. You can always double check what it has been defined as by entering this into your browser console: `GoogleAnalyticsObject`, you will normally see `"ga"` returned, unless you redefined the ga to something else.

**Comment by cfnelson** [comment]
@55 Closing the issue, but would be interested to know how you progressed and if you were able to get it working. 😄
