### ISSUE TITLE
Add GitHub tags under the Description field

### ISSUE THREAD

**Issue by RichardLitt** [okgrow/auto-analytics#7]
These tags should work: "javascript", "analytics", "google-analytics", "segment", "kissmetrics", "mixpanel".

**Comment by ghost** [comment]
@RichardLitt Do you mean in the `package.json` `description` field?

**Comment by RichardLitt** [comment]
Nope. On the front page of the repository. I added these yesterday, so this can be closed, though!

**Comment by ghost** [comment]
Groovy. Thanks.
