### ISSUE TITLE
Currently there is no way to set user id as mentioned in GA link below.

### ISSUE THREAD

**Issue by sarathspillai** [okgrow/auto-analytics#8]
https://support.google.com/analytics/answer/3123666?hl=en

In this step, you can see the line of code that you have to add to your Analytics tracking code:
ga('set', 'userId', {{USER_ID}}); // Set the user ID using signed-in user_id.

Is there any option to do the same using our analytics api?
Could some one please suggest whether it can be supported?

Thanks,
Sarath.

**Comment by pauldowman** [comment]
This is the `identify()` call (we use [analytics.js](https://github.com/segmentio/analytics.js) and it provides a wrapper API on top of the GA API). It's done automatically by this package in some cases, and if you want to do it manually see the documentation here: https://segment.com/docs/sources/website/analytics.js/#identify
